version: '3'
services:
  mongo-app:
    image: falcon007/third-mongo-spring-data:0.0.1-SNAPSHOT
    ports:
      - "8083:8083"
    environment:
      spring.data.mongodb.uri: mongodb://mongo:27017/data
    depends_on:
      - mongo
    networks:
      - my-network
  mongo:
    image: mongo:3.4.7
    ports:
      - "27017:27017"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge